main: world.fluff.FluffWorldIntegration
name: FluffWorldIntegration
version: 1.7.4
author: Fluff
description: Fluff's Plugin
commands:
  points:
    description: (FWMC) Displays FWMC points
    usage: /points [MCusername]
  chatcolor:
    description: (FWMC) Changes your color in the chat
    usage: /chatcolor <color>
  coords:
    description: (FWMC) Broadcast your coordinates
    usage: /coords
  register:
    description: (FWMC) Link your FW account
    usage: /register <FWusername>
  withdraw:
    description: (FWMC) Withdraw FWMC points into a FWMC Points Ticket item
    usage: /withdraw <points to withdraw>
  bedspawn:
    description: (FWMC) Get the location of your bed spawn's location, or broadcast it to other players
    usage: |
       /bedspawn [broadcast]
       Example: /bedspawn - privately tells you of where your bed is
       Example: /bedspawn broadcast - publically broadcasts your bed
  convertxp:
    description: (FWMC) Convert XP levels <-> orbs
    usage: |
       /convertxp [amount] [orbs | levels]
       Example: /convertxp 452 orbs
       Example: /convertxp 15 levels
  dropxp:
    description: (FWMC) Drop your XP orbs onto the ground
    usage: /dropxp <orb count>